### ISSUE TITLE
Settings to disable progress bars

### ISSUE THREAD

**Issue by quentinblampey** [fish-quant/ComSeg#10]
Hello @tdefa, I wanted to know if it would be possible to add a setting to disable the tqdm progress bars from ComSeg?

It has a lot of logs, so when we run ComSeg multiple times (e.g., in Sopa), we don't know how many patches we have already segmented because the "main" progress bar is hidden inside all the logs.

It's pretty easy to disable the print statements using a context manager, but it's difficult to do that for tqdm.

**Comment by tdefa** [comment]
Hello Quentin,

I added an argument "disable_tqdm" in the new comseg version on pip ( like here https://comseg.readthedocs.io/en/latest/userguide/Minimal_example.html)

I can be added in the ```config : dict```  of the function ``` comseg_patch``` of sopa.

It suppress most of the tqdm print

I still have to replace the parameters of ```ComSegDataset``` by ComSegDataset(config) in the fonction of  ```comseg_patch``` to suppress the remaining tqdm print. I can do a PR on sopa this week for this

**Comment by quentinblampey** [comment]
Hello @tdefa, thanks for the quick update!

Don't worry for Sopa, I'll do the update myself (I'm currently working on a branch that is only stable under a certain PR of SpatialData, so it's quite unstable ahah)

I'll test it out soon :)

**Comment by tdefa** [comment]
Ok cool, do not hesitate if you need anything else.

**Comment by quentinblampey** [comment]
By the way, this is an overview of how to use the API for ComSeg with `sopa==2.0.0` (i.e., the next release):

```python
import sopa

### Load the data
sdata = sopa.io.toy_dataset(add_nan_gene_name=False)  # here, we use the toy dataset

### Cellpose
sopa.make_image_patches(sdata, patch_width=1200, patch_overlap=50)
sopa.segmentation.cellpose(sdata, "DAPI", diameter=35)

### Comseg
sopa.make_transcript_patches(sdata, prior_shapes_key="cellpose_boundaries", write_cells_centroids=True)
sopa.segmentation.comseg(sdata, config) # config is optional here
```
I'm trying to simplify the API + add other features!

**Comment by tdefa** [comment]
this looks great indeed !

**Comment by quentinblampey** [comment]
I have tested it, and it works well, thanks!

Now, there are still some warnings, but I can filter them out in Sopa:
````
FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  nn_expression_vector = nn_expression_vector / len(self.community_anndata.obs["node_index"][comm_index])
```

Closing the issue 👍
