### ISSUE TITLE
Typo in function get_anndata_from_result

### ISSUE THREAD

**Issue by NathanProvin** [fish-quant/ComSeg#4]
**Describe the typo**
There is a typo in the function `get_anndata_from_result` in the `comseg/model.py` file.

**Location of the typo**
- File: `comseg/model.py`
- Function: `get_anndata_from_result`
- Line: 851

**Incorrect text**
The parameter `allow_disconnected_polygone` is misspelled

**Correct text**
The correct spelling should be `allow_disconnected_polygon`.

**Additional context**
This typo causes a `NameError` when trying to use the `allow_disconnected_polygon` parameter.

**Comment by tdefa** [comment]
Thanks for noticing ! It is now corrected in the new release comseg version 0.4
